const express = require("express");
const router = express.Router();
const data = require("../data");
const tasksData = data.tasks;

/**
 * GET /api/tasks
 * Shows a list of tasks
 * By default, it will show the first 20 tasks in the collection.
 * If a querystring variable ?skip=n is provided, you will skip the first n tasks.
 * If a querystring variable ?take=y is provided, it will show y number of results.
 * By default, the route will show up to 20 tasks; at most it will show 100 tasks.
 */
router.get("/", async (req, res) => {});

/**
 * GET /api/tasks/:id
 * Shows the task with the supplied ID
 */
router.get("/:id", async (req, res) => {
  try {
    const task = await tasksData.getTaskById(req.params.id);
    res.status(200).json(task);
  } catch (e) {
    res.status(404).json({ error: "Task not found" });
  }
});

/**
 * POST /api/tasks
 * Creates a task with the supplied detail and returns created object
 * fails request if not all details supplied
 */
router.post("/", async (req, res) => {
  const taskInfo = req.body;

  if (!taskInfo) {
    res.status(400).json({ error: "You must provide data to create a task" });
    return;
  }
  if (!taskInfo.title) {
    res.status(400).json({ error: "You must provide a title" });
    return;
  }
  if (!taskInfo.description) {
    res.status(400).json({ error: "You must provide a description" });
    return;
  }
  if (!taskInfo.hoursEtimated) {
    res.status(400).json({ error: "You must provide estimated hours" });
    return;
  }

  try {
    const newTask = await tasksData.createTask(
      taskInfo.title,
      taskInfo.description,
      taskInfo.hoursEtimated
    );
    res.status(200).json(newTask);
  } catch (e) {
    res.sendStatus(500).json({ error: e });
  }
});

/**
 * Updates the task with the supplied ID and returns the new task object
 * task: PUT calls must provide all details of the new state of the object
 * Note: you cannot manipulate comments in this route
 */
router.put("/:id", async (req, res) => {
  let taskInfo = req.body;
  if (!taskInfo) {
    res.status(400).json({ error: "You must provide data to update a task" });
    return;
  }

  //change updatedTask to taskInfo
  if(!taksTask.title || !updatedTask.description || !updatedTask.hoursEtimated || !updatedTask.completed) {
      res.status(400).json({ error: "You must provide all details of the new state" });
      return;
  }

  try {
     await tasksData.getTaskById(req.params.id);
  } catch (e) {
      res.status(404).json({ error: "Task not found" });
      return;
  }

  try {
      
  }

});

/**
 * Updates the task with the supplied ID and returns the new task object
 * task: PATCH calls only provide deltas of the value to update
 * Note: you cannot manipulate comments in this route
 */
router.patch("/:id", async (req, res) => {});

/**
 * Adds a new comment to the task
 * ids must be generated by the server, and not supplied
 */
router.post("/:id/comments", async (req, res) => {});

/**
 * Deletes the comment with an id of commentId on the task with an id of task Id
 */
router.delete("/:taskId/:commentId", async (req, res) => {});

module.exports = router;
